apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-tomcate-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/srinidks/tomcate-argocd-2026.git
    targetRevision: main
    path: manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: tomcat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
