apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-tomcat-app
  namespace: tomcat
  labels:
    app: argocd-tomcat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-tomcat-app
  template:
    metadata:
      labels:
        app: argocd-tomcat-app
    spec:
      containers:
        - name: tomcat-app
          image: srinidks/argocd-tomcat-app:9
          ports:
            - containerPort: 8080
