apiVersion: v1
kind: Service
metadata:
  name: tomcat-app-svc
  namespace: tomcat
spec:
  type: NodePort
  selector:
    app: argocd-tomcat-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
